# .sops.yaml
# ==============================================================================
# SOPS Encryption Rules
# ==============================================================================
creation_rules:
  # Text-based secrets (YAML, JSON, ENV, INI)
  # Uses 'encrypted_regex' to encrypt values but keep keys readable
  - path_regex: .*\.enc\.(yaml|json|env|ini|toml)$
    encrypted_regex: "^(data|stringData|.*_password|.*_secret|.*_key|.*_token)$"
    key_groups:
      - age:
          - "age1wwh5yf2j0jygr8p3z44j32hsf7l6x08sr0gmqzzmfq3wrrfw6v7sxq2fyp"

  # Binary secrets (Archives, Blobs)
  # Encrypts the entire file content
  - path_regex: (.*\.enc\.(tar\.gz|tgz|zip|bin)$|.*fzf\.env\.tar\.gz$)
    key_groups:
      - age:
          - "age1wwh5yf2j0jygr8p3z44j32hsf7l6x08sr0gmqzzmfq3wrrfw6v7sxq2fyp"
