# modules/home/cliphist/default.nix
# ==============================================================================
# Cliphist clipboard history configuration.
# - Installs `cliphist` + `wl-clipboard` (wl-copy / wl-paste)
# - Generates `~/.config/cliphist/config`
# - Optionally runs a Wayland watcher to populate the database
# ==============================================================================

{ config, lib, pkgs, ... }:
let
  cfg = config.my.user.cliphist;

  flagLine = key: value: "${key} ${toString value}";

  # Prefer a fully expanded default path (no "~" surprises).
  defaultDbPath = "${config.xdg.configHome}/cliphist/db";

  configLines = with cfg; [
    "# Generated by Home Manager - do not edit manually."
    (flagLine "-db-path" dbPath)
    (flagLine "-max-items" maxItems)
    (flagLine "-max-dedupe-search" maxDedupeSearch)
    (flagLine "-preview-width" previewWidth)
  ]
  ++ lib.optional (minStoreLength > 0) (flagLine "-min-store-length" minStoreLength)
  ++ lib.optional storeIgnoreSingleCharacter "-store-ignore-single-character"
  ++ lib.optional storeIgnoreEmpty "-store-ignore-empty"
  ++ lib.optional highlightMatch "-highlight-match"
  ++ extraFlags;

  hasWaylandTarget = lib.hasAttrByPath [ "wayland" "systemd" "target" ] config;
  sessionTarget =
    if hasWaylandTarget then config.wayland.systemd.target else "graphical-session.target";

  mkCliphistWatcher = { name, wlPasteArgs }:
    pkgs.writeShellScript "cliphist-watch-${name}.sh" ''
      set -euo pipefail

      if [ "''${XDG_SESSION_TYPE:-}" != "wayland" ]; then
        exit 0
      fi

      exec ${pkgs.wl-clipboard}/bin/wl-paste ${wlPasteArgs} --watch ${pkgs.cliphist}/bin/cliphist store
    '';
in
{
  options.my.user.cliphist = {
    enable = lib.mkEnableOption "cliphist clipboard history configuration";

    autostart = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start wl-paste watchers on login to feed cliphist history.";
    };

    dbPath = lib.mkOption {
      type = lib.types.str;
      default = defaultDbPath;
      description = "Path to cliphist database.";
    };

    maxItems = lib.mkOption {
      type = lib.types.int;
      default = 5000;
      description = "Maximum number of clipboard items to keep.";
    };

    maxDedupeSearch = lib.mkOption {
      type = lib.types.int;
      default = 150;
      description = "How many recent items to scan for duplicates.";
    };

    previewWidth = lib.mkOption {
      type = lib.types.int;
      default = 120;
      description = "Maximum characters to show in previews.";
    };

    minStoreLength = lib.mkOption {
      type = lib.types.int;
      default = 0;
      description = "Ignore entries shorter than this length (0 to disable).";
    };

    storeIgnoreSingleCharacter = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Drop single-character entries.";
    };

    storeIgnoreEmpty = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Drop empty entries.";
    };

    highlightMatch = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Highlight search matches in cliphist output.";
    };

    extraFlags = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Additional raw cliphist flags to append.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      pkgs.cliphist
      pkgs.wl-clipboard
    ];

    xdg.configFile."cliphist/config".text = lib.concatStringsSep "\n" configLines + "\n";

    systemd.user.services = lib.mkIf cfg.autostart {
      cliphist-watch-text = {
        Unit = {
          Description = "cliphist watcher (text)";
          After = [ sessionTarget ];
          PartOf = [ sessionTarget ];
        };
        Service = {
          Type = "simple";
          ExecStart = mkCliphistWatcher {
            name = "text";
            wlPasteArgs = "--type text";
          };
          Restart = "on-failure";
          RestartSec = 1;
        };
        Install.WantedBy = [ sessionTarget ];
      };

      cliphist-watch-image = {
        Unit = {
          Description = "cliphist watcher (image)";
          After = [ sessionTarget ];
          PartOf = [ sessionTarget ];
        };
        Service = {
          Type = "simple";
          ExecStart = mkCliphistWatcher {
            name = "image";
            wlPasteArgs = "--type image";
          };
          Restart = "on-failure";
          RestartSec = 1;
        };
        Install.WantedBy = [ sessionTarget ];
      };
    };
  };
}

