# modules/home/cliphist/default.nix
# ==============================================================================
# Home Manager module for cliphist.
# Exposes my.user options to install packages and write user config.
# Keeps per-user defaults centralized instead of scattered dotfiles.
# Adjust feature flags and templates in the module body below.
# ==============================================================================

{ config, lib, pkgs, ... }:
let
  cfg = config.my.user.cliphist;

  flagLine = key: value: "${key} ${toString value}";

  configLines = with cfg; [
    "# Generated by Home Manager - do not edit manually."
    (flagLine "-db-path" dbPath)
    (flagLine "-max-items" maxItems)
    (flagLine "-max-dedupe-search" maxDedupeSearch)
    (flagLine "-preview-width" previewWidth)
  ]
  ++ lib.optional (minStoreLength > 0) (flagLine "-min-store-length" minStoreLength)
  ++ lib.optional storeIgnoreSingleCharacter "-store-ignore-single-character"
  ++ lib.optional storeIgnoreEmpty "-store-ignore-empty"
  ++ lib.optional highlightMatch "-highlight-match"
  ++ extraFlags;
in {
  options.my.user.cliphist = {
    enable = lib.mkEnableOption "cliphist clipboard history configuration";

    dbPath = lib.mkOption {
      type = lib.types.str;
      default = "~/.config/cliphist/db";
      description = "Path to cliphist database.";
    };

    maxItems = lib.mkOption {
      type = lib.types.int;
      default = 5000;
      description = "Maximum number of clipboard items to keep.";
    };

    maxDedupeSearch = lib.mkOption {
      type = lib.types.int;
      default = 150;
      description = "How many recent items to scan for duplicates.";
    };

    previewWidth = lib.mkOption {
      type = lib.types.int;
      default = 120;
      description = "Maximum characters to show in previews.";
    };

    minStoreLength = lib.mkOption {
      type = lib.types.int;
      default = 0;
      description = "Ignore entries shorter than this length (0 to disable).";
    };

    storeIgnoreSingleCharacter = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Drop single-character entries.";
    };

    storeIgnoreEmpty = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Drop empty entries.";
    };

    highlightMatch = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Highlight search matches in cliphist output.";
    };

    extraFlags = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Additional raw cliphist flags to append.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.cliphist pkgs.wl-clipboard ];

    xdg.configFile."cliphist/config".text = lib.concatStringsSep "\n" configLines + "\n";
  };
}
