# modules/home/mangowc/settings.nix
# ==============================================================================
# MangoWC base settings (config.conf snippet)
# ==============================================================================
{ lib, keyboard, ... }:

let
  kbOptions = lib.concatStringsSep "," (keyboard.options or [ ]);
  kbVariantLine = lib.optionalString (keyboard.variant != null && keyboard.variant != "") ''
    xkb_rules_variant=${keyboard.variant}
  '';
  kbOptionsLine = lib.optionalString (kbOptions != "") ''
    xkb_rules_options=${kbOptions}
  '';
in
{
  main = ''
    # ==============================================================================
    # MangoWC config (generated by nixosc)
    # ==============================================================================

    # Misc
    focus_cross_monitor=0
    focus_cross_tag=0
    focus_on_activate=1
    sloppyfocus=1
    warpcursor=1

    # Scroller / tiling ergonomics (safe defaults)
    scroller_focus_center=0
    smartgaps=0

    # Gaps / borders
    gappih=5
    gappiv=5
    gappoh=10
    gappov=10
    borderpx=3
    border_radius=6
    no_border_when_single=0
    no_radius_when_single=0

    # Keyboard
    repeat_rate=25
    repeat_delay=600
    numlockon=0
    xkb_rules_layout=${keyboard.layout}
    ${kbVariantLine}${kbOptionsLine}

    # Environment (make session identifiable to tools like DMS/Fusuma)
    env=XDG_SESSION_TYPE,wayland
    env=XDG_CURRENT_DESKTOP,mango
    env=XDG_SESSION_DESKTOP,mango
    env=NIXOS_OZONE_WL,1

    # Autostart (runs after Mango is up; has WAYLAND_DISPLAY)
    exec-once=dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE NIXOS_OZONE_WL XCURSOR_THEME XCURSOR_SIZE
    exec-once=systemctl --user reset-failed
    exec-once=systemctl --user start mango-session.target

    # Tags (workspaces)
    # Keep tags visible even when empty (static 1..9).
    tagrule=id:1,no_hide:1
    tagrule=id:2,no_hide:1
    tagrule=id:3,no_hide:1
    tagrule=id:4,no_hide:1
    tagrule=id:5,no_hide:1
    tagrule=id:6,no_hide:1
    tagrule=id:7,no_hide:1
    tagrule=id:8,no_hide:1
    tagrule=id:9,no_hide:1
  '';
}
