# modules/home/mangowc/settings.nix
# ==============================================================================
# MangoWC base settings (config.conf snippet)
# ==============================================================================
{ lib, keyboard, ... }:

let
  kbOptions = lib.concatStringsSep "," (keyboard.options or [ ]);
  kbVariantLine = lib.optionalString (keyboard.variant != null && keyboard.variant != "") ''
    xkb_rules_variant=${keyboard.variant}
  '';
  kbOptionsLine = lib.optionalString (kbOptions != "") ''
    xkb_rules_options=${kbOptions}
  '';
in
{
  main = ''
    # ==============================================================================
    # MangoWC config (generated by nixosc)
    # ==============================================================================

    # Misc
    focus_cross_monitor=0
    focus_cross_tag=0
    focus_on_activate=1
    sloppyfocus=1
    warpcursor=1

    # Scroller / tiling ergonomics (safe defaults)
    scroller_focus_center=0
    smartgaps=0

    # Gaps / borders
    gappih=5
    gappiv=5
    gappoh=10
    gappov=10
    borderpx=3
    border_radius=6
    no_border_when_single=0
    no_radius_when_single=0

    # Keyboard
    repeat_rate=25
    repeat_delay=600
    numlockon=0
    xkb_rules_layout=${keyboard.layout}
    ${kbVariantLine}${kbOptionsLine}
  '';
}

