#!/usr/bin/env bash
# Profile: wkenp
# Type: terminal
# Generated by Semsumo v5.0.0
set -euo pipefail

echo "Initializing wkenp..."

# Switch to initial workspace
if [[ "2" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    # Get current workspace
    CURRENT_WORKSPACE=$(hyprctl activeworkspace -j | grep -o '"id": [0-9]*' | grep -o '[0-9]*' || echo "")
    
    # Only switch if we're not already on the target workspace
    if [[ "$CURRENT_WORKSPACE" != "2" ]]; then
        echo "Switching to workspace 2..."
        hyprctl dispatch workspace "2"
        sleep 1
        echo "Waiting 1 seconds for transition..."
    else
        echo "Already on workspace 2, skipping switch."
    fi
fi

echo "Starting application..."
echo "COMMAND: wezterm "start" "--class" "TmuxKenp" "-e" "tm""
echo "VPN MODE: bypass"

# Start the application with the appropriate VPN mode
case "bypass" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude wezterm "start" "--class" "TmuxKenp" "-e" "tm" &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                wezterm "start" "--class" "TmuxKenp" "-e" "tm" &
            fi
        else
            echo "VPN not connected, starting normally"
            wezterm "start" "--class" "TmuxKenp" "-e" "tm" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        wezterm "start" "--class" "TmuxKenp" "-e" "tm" &
        ;;
esac

# Save PID and wait a moment
APP_PID=$!
mkdir -p "/tmp/sem"
echo "$APP_PID" > "/tmp/sem/wkenp.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "false" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

# Switch to final workspace if needed
if [[ "2" != "0" ]]; then
    # Get current workspace again
    CURRENT_WORKSPACE=$(hyprctl activeworkspace -j | grep -o '"id": [0-9]*' | grep -o '[0-9]*' || echo "")
    
    # Only switch if we're not already on the target final workspace
    if [[ "$CURRENT_WORKSPACE" != "2" ]]; then
        echo "Switching to final workspace 2..."
        if command -v hyprctl >/dev/null 2>&1; then
            hyprctl dispatch workspace "2"
        fi
    else
        echo "Already on final workspace 2, skipping switch."
    fi
fi

exit 0
