#!/usr/bin/env bash
# Profile: mkenp
# Type: terminal
# Generated by Semsumo v5.0.0
set -euo pipefail

echo "Initializing mkenp..."

# Switch to initial workspace
if [[ "2" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    echo "Switching to workspace 2..."
    hyprctl dispatch workspace "2"
    sleep 1
    echo "Waiting 1 seconds for transition..."
fi

echo "Starting application..."
echo "COMMAND: kitty "--class" "TmuxKenp" "-T" "Tmux" "-e" "tm""
echo "VPN MODE: secure"

# Start the application with the appropriate VPN mode
case "secure" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude kitty "--class" "TmuxKenp" "-T" "Tmux" "-e" "tm" &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                kitty "--class" "TmuxKenp" "-T" "Tmux" "-e" "tm" &
            fi
        else
            echo "VPN not connected, starting normally"
            kitty "--class" "TmuxKenp" "-T" "Tmux" "-e" "tm" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        kitty "--class" "TmuxKenp" "-T" "Tmux" "-e" "tm" &
        ;;
esac

# Save PID and wait a moment
APP_PID=$!
mkdir -p "/tmp/sem"
echo "$APP_PID" > "/tmp/sem/mkenp.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "false" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

# Switch to final workspace if needed
if [[ "2" != "0" && "2" != "2" ]]; then
    echo "Switching to final workspace..."
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl dispatch workspace "2"
    fi
fi

exit 0
