#!/usr/bin/env bash
#===============================================================================
# Generated script for spotify in always mode
# Generated on: 2025-03-28 23:32:55
# Do not edit manually - this file is automatically generated
#===============================================================================

# Error handling
set -euo pipefail

# Environment setup
export TMPDIR="/tmp/sem"

# Start session with Semsumo
semsumo start "spotify" "always"

# Exit successfully
exit 0
