#!/usr/bin/env bash
#===============================================================================
# Generated script for Zen-NoVpn in default mode
# Generated on: 2025-03-25 09:42:15
# Do not edit manually - this file is automatically generated
#===============================================================================

# Error handling
set -euo pipefail

# Environment setup
export TMPDIR="/tmp/sem"

# Start session with Semsumo
semsumo start "Zen-NoVpn" "default"

# Exit successfully
exit 0
