#!/usr/bin/env bash
# Profile: mpv
# Type: app
# Generated by Semsumo v5.0.0
set -euo pipefail

echo "Initializing mpv..."

# Switch to initial workspace
if [[ "6" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    echo "Switching to workspace 6..."
    hyprctl dispatch workspace "6"
    sleep 1
    echo "Waiting 1 seconds for transition..."
fi

echo "Starting application..."
echo "COMMAND: mpv "--player-operation-mode=pseudo-gui" "--input-ipc-server=/tmp/mpvsocket""
echo "VPN MODE: bypass"

# Start the application with the appropriate VPN mode
case "bypass" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude mpv "--player-operation-mode=pseudo-gui" "--input-ipc-server=/tmp/mpvsocket" &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                mpv "--player-operation-mode=pseudo-gui" "--input-ipc-server=/tmp/mpvsocket" &
            fi
        else
            echo "VPN not connected, starting normally"
            mpv "--player-operation-mode=pseudo-gui" "--input-ipc-server=/tmp/mpvsocket" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        mpv "--player-operation-mode=pseudo-gui" "--input-ipc-server=/tmp/mpvsocket" &
        ;;
esac

# Save PID and wait a moment
APP_PID=$!
mkdir -p "/tmp/sem"
echo "$APP_PID" > "/tmp/sem/mpv.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "true" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

# Switch to final workspace if needed
if [[ "6" != "0" && "6" != "6" ]]; then
    echo "Switching to final workspace..."
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl dispatch workspace "6"
    fi
fi

exit 0
