#!/usr/bin/env bash
#===============================================================================
# Generated script for Zen-NoVpn
# Generated on: 2025-04-08 02:44:25
# VPN Mode: bypass
# Do not edit manually - this file is automatically generated
#===============================================================================

# Error handling
set -euo pipefail

# Environment setup
export TMPDIR="/tmp/sem"

# Start session with Semsumo
semsumo start "Zen-NoVpn" "bypass"

# Exit successfully
exit 0
