#!/usr/bin/env bash
# Profile: Brave-Youtube
# Type: browser
# Generated by Semsumo v5.0.0
set -euo pipefail

echo "Initializing Brave-Youtube..."

# Switch to initial workspace
if [[ "7" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    echo "Switching to workspace 7..."
    hyprctl dispatch workspace "7"
    sleep 1
    echo "Waiting 1 seconds for transition..."
fi

echo "Starting application..."
echo "COMMAND: profile_brave "--youtube""
echo "VPN MODE: secure"

# Start the application with the appropriate VPN mode
case "secure" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude profile_brave "--youtube" &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                profile_brave "--youtube" &
            fi
        else
            echo "VPN not connected, starting normally"
            profile_brave "--youtube" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        profile_brave "--youtube" &
        ;;
esac

# Save PID and wait a moment
APP_PID=$!
mkdir -p "/tmp/sem"
echo "$APP_PID" > "/tmp/sem/Brave-Youtube.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "true" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

# Switch to final workspace if needed
if [[ "7" != "0" && "7" != "7" ]]; then
    echo "Switching to final workspace..."
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl dispatch workspace "7"
    fi
fi

exit 0
