#!/usr/bin/env bash
# Profile: Zen-Kenp
# Type: browser
# Generated by Semsumo v5.0.0
set -euo pipefail

echo "Initializing Zen-Kenp..."

# Switch to initial workspace
if [[ "1" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    echo "Switching to workspace 1..."
    hyprctl dispatch workspace "1"
    sleep 1
    echo "Waiting 1 seconds for transition..."
fi

echo "Starting application..."
echo "COMMAND: zen "-P" "Kenp" "--class" "Kenp" "--name" "Kenp" "--restore-session""
echo "VPN MODE: secure"

# Start the application with the appropriate VPN mode
case "secure" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude zen "-P" "Kenp" "--class" "Kenp" "--name" "Kenp" "--restore-session" &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                zen "-P" "Kenp" "--class" "Kenp" "--name" "Kenp" "--restore-session" &
            fi
        else
            echo "VPN not connected, starting normally"
            zen "-P" "Kenp" "--class" "Kenp" "--name" "Kenp" "--restore-session" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        zen "-P" "Kenp" "--class" "Kenp" "--name" "Kenp" "--restore-session" &
        ;;
esac

# Save PID and wait a moment
APP_PID=$!
mkdir -p "/tmp/sem"
echo "$APP_PID" > "/tmp/sem/Zen-Kenp.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "false" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

# Switch to final workspace if needed
if [[ "1" != "0" && "1" != "1" ]]; then
    echo "Switching to final workspace..."
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl dispatch workspace "1"
    fi
fi

exit 0
