# modules/home/niri/default.nix
# ==============================================================================
# Home module for the niri compositor with DMS integration and kitty on Super+Return.
# Generates a clean config.kdl using absolute paths; starts dms/nirius/niriswitcher
# at session startup and maps keybinds similar to the Hyprland setup. Includes
# core niri navigation binds (focus/move/close/overview/screenshot).
# ==============================================================================
{ config, lib, pkgs, ... }:
let
  cfg = config.my.desktop.niri;
  username = config.home.username;
  userBin = "/etc/profiles/per-user/${username}/bin";

  kittyCmd = "${pkgs.kitty}/bin/kitty";
  dmsCmd = "${userBin}/dms";
  niriusCmd = "${pkgs.nirius}/bin/niriusd";
  niriswitcherCmd = "${pkgs.niriswitcher}/bin/niriswitcher";

  niriConfig = ''
    // niri config autogenerated by Home Manager (nixosc)
    environment {
      XDG_CURRENT_DESKTOP "niri";
    }

    spawn-at-startup "${niriusCmd}";
    spawn-at-startup "${niriswitcherCmd}";
    spawn-at-startup "${dmsCmd}" "run";

    input {
      keyboard {
        mod-key "Super"
        numlock
        xkb {
          layout "tr"
          variant "f"
          options "ctrl:nocaps"
        }
      }
    }

    binds {
      // Terminals
      Super+Return { spawn "${kittyCmd}"; }

      // Core navigation (close/quit/focus/move)
      Super+Q { close-window; }
      Super+Shift+E { quit skip-confirmation=true; }
      Super+Left { focus-column-left; }
      Super+Right { focus-column-right; }
      Super+Up { focus-workspace-up; }
      Super+Down { focus-workspace-down; }
      Super+Shift+Left { move-column-left; }
      Super+Shift+Right { move-column-right; }
      Super+Shift+Up { move-window-up; }
      Super+Shift+Down { move-window-down; }
      Super+Ctrl+Left { move-workspace-to-output-left; }
      Super+Ctrl+Right { move-workspace-to-output-right; }
      Super+Ctrl+Up { move-workspace-to-output-up; }
      Super+Ctrl+Down { move-workspace-to-output-down; }
      Super+O { toggle-fullscreen; }
      Super+F { toggle-maximize; }
      Super+Esc { toggle-keyboard-shortcuts-inhibit; }
      Super+Tab { overview; }

      // Built-in screenshots
      Print { screenshot; }
      Ctrl+Print { screenshot-screen write-to-disk=false; }
      Alt+Print { screenshot-window write-to-disk=false; }

      // DMS launchers & power
      Super+Space { spawn "${dmsCmd}" "ipc" "call" "spotlight" "toggle"; }
      Super+Backspace { spawn "${dmsCmd}" "ipc" "call" "powermenu" "toggle"; }
      Super+Delete { spawn "${dmsCmd}" "ipc" "call" "lock" "lock"; }
      Alt+L { spawn "${dmsCmd}" "ipc" "call" "lock" "lock"; }
      Super+Shift+Delete { spawn "${dmsCmd}" "ipc" "call" "inhibit" "toggle"; }

      // Dash & panels
      Super+D { spawn "${dmsCmd}" "ipc" "call" "dash" "toggle" ""; }
      Super+C { spawn "${dmsCmd}" "ipc" "call" "control-center" "toggle"; }
      Super+N { spawn "${dmsCmd}" "ipc" "call" "notifications" "toggle"; }
      Super+comma { spawn "${dmsCmd}" "ipc" "call" "settings" "focusOrToggle"; }
      Super+Shift+P { spawn "${dmsCmd}" "ipc" "call" "processlist" "focusOrToggle"; }
      Super+Shift+K { spawn "${dmsCmd}" "ipc" "call" "settings" "openWith" "keybinds"; }

      // Theme & night mode
      Super+Shift+T { spawn "${dmsCmd}" "ipc" "call" "theme" "toggle"; }
      Super+Shift+N { spawn "${dmsCmd}" "ipc" "call" "night" "toggle"; }

      // Bar & Dock
      Super+B { spawn "${dmsCmd}" "ipc" "call" "bar" "toggle" "index" "0"; }
      Super+Shift+B { spawn "${dmsCmd}" "ipc" "call" "dock" "toggle"; }
      Super+Ctrl+B { spawn "${dmsCmd}" "ipc" "call" "bar" "toggleAutoHide" "index" "0"; }

      // Wallpaper
      Super+Y { spawn "${dmsCmd}" "ipc" "call" "dankdash" "wallpaper"; }
      Super+W { spawn "${dmsCmd}" "ipc" "call" "wallpaper" "next"; }
      Super+Shift+W { spawn "${dmsCmd}" "ipc" "call" "wallpaper" "prev"; }
      Super+Ctrl+W { spawn "${dmsCmd}" "ipc" "call" "file" "browse" "wallpaper"; }

      // Notes, clipboard, cheatsheet
      Super+Ctrl+N { spawn "${dmsCmd}" "ipc" "call" "notepad" "open"; }
      Super+V { spawn "${dmsCmd}" "ipc" "call" "clipboard" "toggle"; }
      Super+slash { spawn "${dmsCmd}" "ipc" "call" "keybinds" "toggle" "hyprland"; }

      // Audio & brightness (XF86 keys)
      XF86AudioRaiseVolume { spawn "${dmsCmd}" "ipc" "call" "audio" "increment" "3"; }
      XF86AudioLowerVolume { spawn "${dmsCmd}" "ipc" "call" "audio" "decrement" "3"; }
      XF86AudioMute { spawn "${dmsCmd}" "ipc" "call" "audio" "mute"; }
      XF86AudioMicMute { spawn "${dmsCmd}" "ipc" "call" "audio" "micmute"; }
      XF86AudioPlay { spawn "${dmsCmd}" "ipc" "call" "mpris" "playPause"; }
      XF86AudioNext { spawn "${dmsCmd}" "ipc" "call" "mpris" "next"; }
      XF86AudioPrev { spawn "${dmsCmd}" "ipc" "call" "mpris" "previous"; }
      XF86AudioStop { spawn "${dmsCmd}" "ipc" "call" "mpris" "stop"; }
      XF86MonBrightnessUp { spawn "${dmsCmd}" "ipc" "call" "brightness" "increment" "5"; }
      XF86MonBrightnessDown { spawn "${dmsCmd}" "ipc" "call" "brightness" "decrement" "5"; }
      Super+Alt+A { spawn "${dmsCmd}" "ipc" "call" "audio" "cycleoutput"; }
      Super+Alt+B { spawn "${dmsCmd}" "ipc" "call" "brightness" "toggleExponential"; }
    }
  '';

in
{
  options.my.desktop.niri = {
    enable = lib.mkEnableOption "Niri compositor (Wayland) configuration";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.niri;
      description = "Niri compositor package.";
    };
    enableNirius = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install nirius daemon + cli helpers.";
    };
    enableNiriswitcher = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install niriswitcher application switcher.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      [ cfg.package ]
      ++ lib.optional cfg.enableNirius pkgs.nirius
      ++ lib.optional cfg.enableNiriswitcher pkgs.niriswitcher;

    xdg.configFile."niri/config.kdl".text = niriConfig;
  };
}
