# modules/home/niri/default.nix
# ==============================================================================
# Home module for the niri compositor with DMS integration and kitty on Super+Return.
# Generates a clean config.kdl using absolute paths; starts dms/nirius/niriswitcher
# at session startup and maps keybinds similar to the Hyprland setup.
# ==============================================================================
{ config, lib, pkgs, ... }:
let
  cfg = config.my.desktop.niri;
  username = config.home.username;
  userBin = "/etc/profiles/per-user/${username}/bin";

  kittyCmd = "${pkgs.kitty}/bin/kitty";
  dmsCmd = "${userBin}/dms";
  niriusCmd = "${pkgs.nirius}/bin/niriusd";
  niriswitcherCmd = "${pkgs.niriswitcher}/bin/niriswitcher";

  # Helper to render a spawn bind
  bindSpawn = key: args: ''
    bind {
      key = "${key}";
      command = "spawn";
      args = ${args};
    }
  '';

  dms = cmd: ''["${dmsCmd}", "ipc", "call", ${cmd}]'';

  niriConfig = ''
    # niri config autogenerated by Home Manager (nixosc)
    env {
      XDG_CURRENT_DESKTOP = "niri";
    }

    spawn-at-startup "${niriusCmd}";
    spawn-at-startup "${niriswitcherCmd}";
    spawn-at-startup "${dmsCmd}" "run";

    binds {
      ${bindSpawn "Super+Return" ''["${kittyCmd}"]''}

      # Launchers & power
      ${bindSpawn "Super+Space" (dms ''"spotlight", "toggle"'' )}
      ${bindSpawn "Super+Backspace" (dms ''"powermenu", "toggle"'' )}
      ${bindSpawn "Super+Delete" (dms ''"lock", "lock"'' )}
      ${bindSpawn "Alt+L" (dms ''"lock", "lock"'' )}
      ${bindSpawn "Super+Shift+Delete" (dms ''"inhibit", "toggle"'' )}

      # Dash & panels
      ${bindSpawn "Super+D" (dms ''"dash", "toggle", ""'' )}
      ${bindSpawn "Super+C" (dms ''"control-center", "toggle"'' )}
      ${bindSpawn "Super+N" (dms ''"notifications", "toggle"'' )}
      ${bindSpawn "Super+comma" (dms ''"settings", "focusOrToggle"'' )}
      ${bindSpawn "Super+Shift+P" (dms ''"processlist", "focusOrToggle"'' )}
      ${bindSpawn "Super+Shift+K" (dms ''"settings", "openWith", "keybinds"'' )}

      # Theme & night mode
      ${bindSpawn "Super+Shift+T" (dms ''"theme", "toggle"'' )}
      ${bindSpawn "Super+Shift+N" (dms ''"night", "toggle"'' )}

      # Bar & Dock
      ${bindSpawn "Super+B" (dms ''"bar", "toggle", "index", "0"'' )}
      ${bindSpawn "Super+Shift+B" (dms ''"dock", "toggle"'' )}
      ${bindSpawn "Super+Ctrl+B" (dms ''"bar", "toggleAutoHide", "index", "0"'' )}

      # Wallpaper
      ${bindSpawn "Super+Y" (dms ''"dankdash", "wallpaper"'' )}
      ${bindSpawn "Super+W" (dms ''"wallpaper", "next"'' )}
      ${bindSpawn "Super+Shift+W" (dms ''"wallpaper", "prev"'' )}
      ${bindSpawn "Super+Ctrl+W" (dms ''"file", "browse", "wallpaper"'' )}

      # Notes, clipboard, cheatsheet
      ${bindSpawn "Super+Ctrl+N" (dms ''"notepad", "open"'' )}
      ${bindSpawn "Super+V" (dms ''"clipboard", "toggle"'' )}
      ${bindSpawn "Super+slash" (dms ''"keybinds", "toggle", "hyprland"'' )}

      # Audio & brightness (XF86 keys)
      ${bindSpawn "XF86AudioRaiseVolume" (dms ''"audio", "increment", "3"'' )}
      ${bindSpawn "XF86AudioLowerVolume" (dms ''"audio", "decrement", "3"'' )}
      ${bindSpawn "XF86AudioMute" (dms ''"audio", "mute"'' )}
      ${bindSpawn "XF86AudioMicMute" (dms ''"audio", "micmute"'' )}
      ${bindSpawn "XF86AudioPlay" (dms ''"mpris", "playPause"'' )}
      ${bindSpawn "XF86AudioNext" (dms ''"mpris", "next"'' )}
      ${bindSpawn "XF86AudioPrev" (dms ''"mpris", "previous"'' )}
      ${bindSpawn "XF86AudioStop" (dms ''"mpris", "stop"'' )}
      ${bindSpawn "XF86MonBrightnessUp" (dms ''"brightness", "increment", "5"'' )}
      ${bindSpawn "XF86MonBrightnessDown" (dms ''"brightness", "decrement", "5"'' )}
      ${bindSpawn "Super+Alt+A" (dms ''"audio", "cycleoutput"'' )}
      ${bindSpawn "Super+Alt+B" (dms ''"brightness", "toggleExponential"'' )}
    }
  '';
in
{
  options.my.desktop.niri = {
    enable = lib.mkEnableOption "Niri compositor (Wayland) configuration";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.niri;
      description = "Niri compositor package.";
    };
    enableNirius = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install nirius daemon + cli helpers.";
    };
    enableNiriswitcher = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install niriswitcher application switcher.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      [ cfg.package ]
      ++ lib.optional cfg.enableNirius pkgs.nirius
      ++ lib.optional cfg.enableNiriswitcher pkgs.niriswitcher;

    xdg.configFile."niri/config.kdl".text = niriConfig;
  };
}
