# modules/home/niri/default.nix
# ==============================================================================
# Home module for the niri compositor with DMS-friendly keybinds.
# Installs niri plus helpers (nirius daemon + niriswitcher) and writes a
# config.kdl containing DMS IPC shortcuts modeled after the Hyprland setup.
# ==============================================================================
{ config, lib, pkgs, ... }:
let
  cfg = config.my.desktop.niri;

  niriConfig = ''
    # niri config autogenerated by Home Manager (nixosc)
    env {
      XDG_CURRENT_DESKTOP = "niri";
    }

    # Start helper daemons
    spawn-at-startup "niriusd"
    spawn-at-startup "niriswitcher"

    # Keybindings (DMS-centric, mirrors Hyprland defaults)
    binds {
      # Launchers & power
      "Super+Space" = spawn "dms ipc call spotlight toggle";
      "Super+Backspace" = spawn "dms ipc call powermenu toggle";
      "Super+Delete" = spawn "dms ipc call lock lock";
      "Alt+L" = spawn "dms ipc call lock lock";
      "Super+Shift+Delete" = spawn "dms ipc call inhibit toggle";

      # Dash & panels
      "Super+D" = spawn "dms ipc call dash toggle \"\"";
      "Super+C" = spawn "dms ipc call control-center toggle";
      "Super+N" = spawn "dms ipc call notifications toggle";
      "Super+comma" = spawn "dms ipc call settings focusOrToggle";
      "Super+Shift+P" = spawn "dms ipc call processlist focusOrToggle";
      "Super+Shift+K" = spawn "dms ipc call settings openWith keybinds";

      # Theme & night mode
      "Super+Shift+T" = spawn "dms ipc call theme toggle";
      "Super+Shift+N" = spawn "dms ipc call night toggle";

      # Bar & Dock
      "Super+B" = spawn "dms ipc call bar toggle index 0";
      "Super+Shift+B" = spawn "dms ipc call dock toggle";
      "Super+Ctrl+B" = spawn "dms ipc call bar toggleAutoHide index 0";

      # Wallpaper
      "Super+Y" = spawn "dms ipc call dankdash wallpaper";
      "Super+W" = spawn "dms ipc call wallpaper next";
      "Super+Shift+W" = spawn "dms ipc call wallpaper prev";
      "Super+Ctrl+W" = spawn "dms ipc call file browse wallpaper";

      # Notes, clipboard, cheatsheet
      "Super+Ctrl+N" = spawn "dms ipc call notepad open";
      "Super+V" = spawn "dms ipc call clipboard toggle";
      "Super+slash" = spawn "dms ipc call keybinds toggle hyprland"; # provider:hyprland cheatsheet

      # Audio & brightness (XF86 keys)
      "XF86AudioRaiseVolume" = spawn "dms ipc call audio increment 3";
      "XF86AudioLowerVolume" = spawn "dms ipc call audio decrement 3";
      "XF86AudioMute" = spawn "dms ipc call audio mute";
      "XF86AudioMicMute" = spawn "dms ipc call audio micmute";
      "XF86AudioPlay" = spawn "dms ipc call mpris playPause";
      "XF86AudioNext" = spawn "dms ipc call mpris next";
      "XF86AudioPrev" = spawn "dms ipc call mpris previous";
      "XF86AudioStop" = spawn "dms ipc call mpris stop";
      "XF86MonBrightnessUp" = spawn "dms ipc call brightness increment 5";
      "XF86MonBrightnessDown" = spawn "dms ipc call brightness decrement 5";
      "Super+Alt+A" = spawn "dms ipc call audio cycleoutput";
      "Super+Alt+B" = spawn "dms ipc call brightness toggleExponential";
    }
  '';
in
{
  options.my.desktop.niri = {
    enable = lib.mkEnableOption "Niri compositor (Wayland) configuration";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.niri;
      description = "Niri compositor package.";
    };
    enableNirius = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install nirius daemon + cli helpers.";
    };
    enableNiriswitcher = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install niriswitcher application switcher.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      [ cfg.package ]
      ++ lib.optional cfg.enableNirius pkgs.nirius
      ++ lib.optional cfg.enableNiriswitcher pkgs.niriswitcher;

    # Main niri configuration
    xdg.configFile."niri/config.kdl".text = niriConfig;
  };
}
