# modules/home/brave/theme.nix
# ==============================================================================
# Brave Catppuccin theme helper: writes Stylus-compatible CSS and a helper
# to re-apply Catppuccin colors. Relies on theme/extension installs from
# extensions.nix (Catppuccin theme, Dark Reader, Stylus).
# ==============================================================================

{ config, pkgs, lib, ... }:

let
  hmLib = lib.hm or config.lib;
  dag = hmLib.dag or config.lib.dag;
  # Check whether Catppuccin integration is desired
  catppuccinEnabled =
    (config.catppuccin.enable or false)
    || (config.my.browser.brave.enableCatppuccinTheme or false);

  flavor = (config.catppuccin.flavor or "mocha");
  accent = (config.catppuccin.accent or "mauve");

  # Catppuccin Chrome Theme extension IDs (reference only)
  catppuccinThemeIds = {
    mocha     = "bkkmolkhemgaeaeggcmfbghljjjoofoh";
    macchiato = "cmpdlhmnmjhihmcfnigoememnffkimlk";
    frappe    = "olhelnoplefjdmncknfphenjclimckaf";
    latte     = "jhjnalhegpceacdhbplhnakmkdliaddd";
  };

  themeId = catppuccinThemeIds.${flavor};

  # NOTE: This list is kept as reference. Actual installation is handled
  #       by extensions.nix (if configured) or manual user action.
  themeExtensions = [
    { id = themeId;                               name = "Catppuccin ${flavor}"; }
    { id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";    name = "Dark Reader"; }
    { id = "clngdbkpkpeebahjckkjfobafhncgmne";    name = "Stylus"; }
  ];

  # Catppuccin color palette
  catppuccinColors = {
    mocha = {
      base     = "#1e1e2e"; text  = "#cdd6f4";
      blue     = "#89b4fa"; mauve = "#cba6f7";
      red      = "#f38ba8"; green = "#a6e3a1";
      yellow   = "#f9e2af"; peach = "#fab387";
      surface0 = "#313244"; surface1 = "#45475a";
    };
    macchiato = {
      base     = "#24273a"; text  = "#cad3f5";
      blue     = "#8aadf4"; mauve = "#c6a0f6";
      red      = "#ed8796"; green = "#a6da95";
      yellow   = "#eed49f"; peach = "#f5a97f";
      surface0 = "#363a4f"; surface1 = "#494d64";
    };
    frappe = {
      base     = "#303446"; text  = "#c6d0f5";
      blue     = "#8caaee"; mauve = "#ca9ee6";
      red      = "#e78284"; green = "#a6d189";
      yellow   = "#e5c890"; peach = "#ef9f76";
      surface0 = "#414559"; surface1 = "#51576d";
    };
    latte = {
      base     = "#eff1f5"; text  = "#4c4f69";
      blue     = "#1e66f5"; mauve = "#8839ef";
      red      = "#d20f39"; green = "#40a02b";
      yellow   = "#df8e1d"; peach = "#fe640b";
      surface0 = "#ccd0da"; surface1 = "#bcc0cc";
    };
  };

  colors = catppuccinColors.${flavor};

  # Stylus-compatible CSS snippet
  stylusCSS = ''
    /* Catppuccin ${flavor} - Auto-generated by NixOS (Brave + Stylus) */

    :root {
      /* Base colors */
      --catppuccin-base: ${colors.base};
      --catppuccin-text: ${colors.text};
      --catppuccin-surface0: ${colors.surface0};
      --catppuccin-surface1: ${colors.surface1};

      /* Accent colors */
      --catppuccin-blue: ${colors.blue};
      --catppuccin-mauve: ${colors.mauve};
      --catppuccin-red: ${colors.red};
      --catppuccin-green: ${colors.green};
      --catppuccin-yellow: ${colors.yellow};
      --catppuccin-peach: ${colors.peach};

      /* Active accent */
      --catppuccin-accent: ${colors.${accent}};
    }

    /* Dark mode override for websites */
    @media (prefers-color-scheme: dark) {
      html {
        background-color: var(--catppuccin-base) !important;
        color: var(--catppuccin-text) !important;
      }

      body {
        background-color: var(--catppuccin-base) !important;
        color: var(--catppuccin-text) !important;
      }

      a {
        color: var(--catppuccin-accent) !important;
      }

      a:hover {
        color: var(--catppuccin-blue) !important;
      }

      ::selection {
        background-color: var(--catppuccin-accent) !important;
        color: var(--catppuccin-base) !important;
      }

      /* Chromium scrollbar styling */
      ::-webkit-scrollbar {
        width: 12px;
        height: 12px;
      }

      ::-webkit-scrollbar-track {
        background: var(--catppuccin-base);
      }

      ::-webkit-scrollbar-thumb {
        background: var(--catppuccin-surface1);
        border-radius: 6px;
      }

      ::-webkit-scrollbar-thumb:hover {
        background: var(--catppuccin-accent);
      }
    }
  '';

  # Dark Reader style reference (not written anywhere by default)
  darkReaderConfig = {
    enabled = true;
    theme = {
      mode       = 1; # Dark mode
      brightness = 100;
      contrast   = 100;
      sepia      = 0;
    };
    customTheme = {
      background = colors.base;
      text       = colors.text;
      link       = colors.${accent};
      selection  = colors.${accent};
    };
  };

  profilePath = ".config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}";

in
{
  config = lib.mkIf (config.my.browser.brave.enable && catppuccinEnabled) {

    # -------------------------------------------------------------------------
    # Write Stylus CSS into profile
    # -------------------------------------------------------------------------

    home.activation.braveTheme = dag.entryAfter [ "writeBoundary" ] ''
      PROFILE_DIR="$HOME/${profilePath}"
      STYLUS_DIR="$PROFILE_DIR/Stylus"

      if [ ! -d "$STYLUS_DIR" ]; then
        $DRY_RUN_CMD mkdir -p "$STYLUS_DIR"
      fi

      $DRY_RUN_CMD cat > "$STYLUS_DIR/catppuccin-${flavor}.user.css" << 'EOFCSS'
${stylusCSS}
EOFCSS

      echo "Installed Catppuccin ${flavor} Stylus CSS for Brave profile '${config.my.browser.brave.profile}'."
    '';

    # -------------------------------------------------------------------------
    # Optional Stylus configuration snapshot (for manual import)
    # -------------------------------------------------------------------------
    # This is not automatically imported by Stylus; it is provided as a
    # reference or for manual usage.

    home.file.".local/share/brave-stylus-config.json" = {
      text = builtins.toJSON {
        styles = [
          {
            name    = "Catppuccin ${flavor}";
            enabled = true;
            sections = [
              { code = stylusCSS; }
            ];
            updateUrl   = null;
            url         = null;
            usercssData = null;
          }
        ];
      };
    };

    # -------------------------------------------------------------------------
    # Theme-related session variables
    # -------------------------------------------------------------------------

    home.sessionVariables =
      {
        BRAVE_ENABLE_DARK_MODE = "1";
      }
      // (lib.optionalAttrs (flavor != "latte") {
        GTK_THEME = "Catppuccin-${flavor}";
      });

    # -------------------------------------------------------------------------
    # Theme helper script
    # -------------------------------------------------------------------------

    home.file.".local/bin/brave-apply-theme" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Apply Catppuccin ${flavor} theme assets for Brave

        PROFILE_DIR="$HOME/${profilePath}"
        STYLUS_DIR="$PROFILE_DIR/Stylus"

        echo "==> Applying Catppuccin ${flavor} theme for Brave"
        echo "Profile: ${config.my.browser.brave.profile}"
        echo "Profile directory: $PROFILE_DIR"
        echo "Theme ID (Chrome Web Store): ${themeId}"
        echo

        mkdir -p "$STYLUS_DIR"

        if [ -f "$STYLUS_DIR/catppuccin-${flavor}.user.css" ]; then
          echo "✓ Stylus CSS already exists"
        else
          echo "Creating Stylus CSS..."
          cat > "$STYLUS_DIR/catppuccin-${flavor}.user.css" << 'EOFCSS'
${stylusCSS}
EOFCSS
          echo "✓ Stylus CSS created"
        fi

        echo
        echo "Recommended setup:"
        echo "  1. Install/enable Catppuccin ${flavor} Chrome theme extension (ID: ${themeId})."
        echo "  2. Install/enable Stylus and Dark Reader extensions."
        echo "  3. In Stylus, create/import a style using the CSS at:"
        echo "     $STYLUS_DIR/catppuccin-${flavor}.user.css"
        echo "  4. Restart Brave."
      '';
    };

    # -------------------------------------------------------------------------
    # Theme aliases
    # -------------------------------------------------------------------------

    home.shellAliases = {
      brave-theme      = "brave-apply-theme";
      brave-theme-css  = "cat ~/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}/Stylus/catppuccin-${flavor}.user.css";
      brave-theme-edit = ''${EDITOR:-nvim} ~/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}/Stylus/catppuccin-${flavor}.user.css'';
    };
  };
}
