# modules/home/brave/theme.nix
# ==============================================================================
# Brave Browser Catppuccin Theme Configuration - Fixed Version
# ==============================================================================
# Bu konfigürasyon Catppuccin temasını extension olarak yükler
# 
# ÖNEMLİ:
# - Theme extension otomatik yüklenir
# - Kullanıcı theme ayarlarını değiştirebilir
# - Sistem tema ayarları ile senkronize çalışır
#
# Author: Kenan Pelit
# ==============================================================================
{ config, pkgs, lib, ... }:

let
  # Merkezi catppuccin konfigürasyonundan ayarları al
  catppuccinEnabled = config.catppuccin.enable or config.my.browser.brave.enableCatppuccinTheme;
  flavor = config.catppuccin.flavor or "mocha";
  accent = config.catppuccin.accent or "mauve";

  # Catppuccin Chrome Theme extension IDs
  catppuccinThemeIds = {
    mocha = "bkkmolkhemgaeaeggcmfbghljjjoofoh";
    macchiato = "cmpdlhmnmjhihmcfnigoememnffkimlk";
    frappe = "olhelnoplefjdmncknfphenjclimckaf";
    latte = "jhjnalhegpceacdhbplhnakmkdliaddd";
  };

  themeId = catppuccinThemeIds.${flavor};

  # Theme extensions listesi
  themeExtensions = [
    { id = themeId; name = "Catppuccin ${flavor}"; }
    { id = "eimadpbcbfnmbkopoojfekhnkhdbieeh"; name = "Dark Reader"; }
    { id = "clngdbkpkpeebahjckkjfobafhncgmne"; name = "Stylus"; }
  ];

  # Catppuccin color definitions
  catppuccinColors = {
    mocha = {
      base = "#1e1e2e"; text = "#cdd6f4";
      blue = "#89b4fa"; mauve = "#cba6f7";
      red = "#f38ba8"; green = "#a6e3a1";
      yellow = "#f9e2af"; peach = "#fab387";
      surface0 = "#313244"; surface1 = "#45475a";
    };
    macchiato = {
      base = "#24273a"; text = "#cad3f5";
      blue = "#8aadf4"; mauve = "#c6a0f6";
      red = "#ed8796"; green = "#a6da95";
      yellow = "#eed49f"; peach = "#f5a97f";
      surface0 = "#363a4f"; surface1 = "#494d64";
    };
    frappe = {
      base = "#303446"; text = "#c6d0f5";
      blue = "#8caaee"; mauve = "#ca9ee6";
      red = "#e78284"; green = "#a6d189";
      yellow = "#e5c890"; peach = "#ef9f76";
      surface0 = "#414559"; surface1 = "#51576d";
    };
    latte = {
      base = "#eff1f5"; text = "#4c4f69";
      blue = "#1e66f5"; mauve = "#8839ef";
      red = "#d20f39"; green = "#40a02b";
      yellow = "#df8e1d"; peach = "#fe640b";
      surface0 = "#ccd0da"; surface1 = "#bcc0cc";
    };
  };

  colors = catppuccinColors.${flavor};

  # Stylus için custom CSS
  stylusCSS = ''
    /* Catppuccin ${flavor} - Auto-generated by NixOS */
    /* This CSS is injected by Stylus extension */
    
    :root {
      /* Base colors */
      --catppuccin-base: ${colors.base};
      --catppuccin-text: ${colors.text};
      --catppuccin-surface0: ${colors.surface0};
      --catppuccin-surface1: ${colors.surface1};
      
      /* Accent colors */
      --catppuccin-blue: ${colors.blue};
      --catppuccin-mauve: ${colors.mauve};
      --catppuccin-red: ${colors.red};
      --catppuccin-green: ${colors.green};
      --catppuccin-yellow: ${colors.yellow};
      --catppuccin-peach: ${colors.peach};
      
      /* Active accent */
      --catppuccin-accent: ${colors.${accent}};
    }
    
    /* Dark mode override for websites */
    @media (prefers-color-scheme: dark) {
      html {
        background-color: var(--catppuccin-base) !important;
        color: var(--catppuccin-text) !important;
      }
      
      body {
        background-color: var(--catppuccin-base) !important;
        color: var(--catppuccin-text) !important;
      }
      
      /* Common element styling */
      a {
        color: var(--catppuccin-accent) !important;
      }
      
      a:hover {
        color: var(--catppuccin-blue) !important;
      }
      
      /* Selection colors */
      ::selection {
        background-color: var(--catppuccin-accent) !important;
        color: var(--catppuccin-base) !important;
      }
      
      /* Scrollbar styling for Chromium */
      ::-webkit-scrollbar {
        width: 12px;
        height: 12px;
      }
      
      ::-webkit-scrollbar-track {
        background: var(--catppuccin-base);
      }
      
      ::-webkit-scrollbar-thumb {
        background: var(--catppuccin-surface1);
        border-radius: 6px;
      }
      
      ::-webkit-scrollbar-thumb:hover {
        background: var(--catppuccin-accent);
      }
    }
  '';

  # Dark Reader settings
  darkReaderConfig = {
    enabled = true;
    theme = {
      mode = 1; # Dark mode
      brightness = 100;
      contrast = 100;
      sepia = 0;
    };
    customTheme = {
      background = colors.base;
      text = colors.text;
      link = colors.${accent};
      selection = colors.${accent};
    };
  };

in {
  config = lib.mkIf (config.my.browser.brave.enable && catppuccinEnabled) {
    
    # ========================================================================
    # Theme Extensions Installation
    # ========================================================================
    # Extension yönetimi extensions.nix dosyası tarafından yapılıyor
    # Burada sadece theme-specific ayarları yapıyoruz
    
    # Theme için extension policy ekle
    home.activation.braveTheme = lib.hm.dag.entryAfter ["writeBoundary"] ''
      PROFILE_DIR="$HOME/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}"
      
      # Stylus için CSS dosyası oluştur
      STYLUS_DIR="$PROFILE_DIR/Stylus"
      if [ ! -d "$STYLUS_DIR" ]; then
        $DRY_RUN_CMD mkdir -p "$STYLUS_DIR"
      fi
      
      # CSS dosyasını yaz
      $DRY_RUN_CMD cat > "$STYLUS_DIR/catppuccin-${flavor}.user.css" << 'EOFCSS'
      ${stylusCSS}
EOFCSS
      
      echo "Installed Catppuccin ${flavor} theme CSS for Stylus"
    '';

    # ========================================================================
    # Stylus Configuration
    # ========================================================================
    
    home.file.".local/share/brave-stylus-config.json" = {
      text = builtins.toJSON {
        styles = [
          {
            name = "Catppuccin ${flavor}";
            enabled = true;
            sections = [
              {
                code = stylusCSS;
              }
            ];
            updateUrl = null;
            url = null;
            usercssData = null;
          }
        ];
      };
    };

    # ========================================================================
    # Theme Session Variables
    # ========================================================================
    
    home.sessionVariables = {
      BRAVE_ENABLE_DARK_MODE = "1";
      GTK_THEME = lib.mkIf (flavor != "latte") "Catppuccin-${flavor}";
    };

    # ========================================================================
    # Theme Helper Scripts
    # ========================================================================
    
    home.file.".local/bin/brave-apply-theme" = {
      text = ''
        #!/usr/bin/env bash
        # Apply Catppuccin ${flavor} theme to Brave
        
        PROFILE_DIR="$HOME/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}"
        
        echo "==> Applying Catppuccin ${flavor} theme..."
        echo "Profile: ${config.my.browser.brave.profile}"
        echo "Theme ID: ${themeId}"
        echo ""
        
        # Check if Stylus CSS exists
        if [ -f "$PROFILE_DIR/Stylus/catppuccin-${flavor}.user.css" ]; then
          echo "✓ Stylus CSS found"
        else
          echo "✗ Stylus CSS not found, creating..."
          mkdir -p "$PROFILE_DIR/Stylus"
          cat > "$PROFILE_DIR/Stylus/catppuccin-${flavor}.user.css" << 'EOFCSS'
${stylusCSS}
EOFCSS
          echo "✓ Stylus CSS created"
        fi
        
        echo ""
        echo "Theme components:"
        echo "  • Catppuccin ${flavor} Chrome Theme (Extension)"
        echo "  • Dark Reader (Extension)"
        echo "  • Stylus with custom CSS (Extension)"
        echo ""
        echo "Next steps:"
        echo "  1. Open brave://extensions/"
        echo "  2. Enable all theme-related extensions"
        echo "  3. Configure Stylus to use the custom CSS"
        echo "  4. Restart Brave"
      '';
      executable = true;
    };

    # ========================================================================
    # Shell Aliases
    # ========================================================================
    
    home.shellAliases = {
      brave-theme = "brave-apply-theme";
      brave-theme-css = "cat ~/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}/Stylus/catppuccin-${flavor}.user.css";
      brave-theme-edit = "\${EDITOR:-nvim} ~/.config/BraveSoftware/Brave-Browser/${config.my.browser.brave.profile}/Stylus/catppuccin-${flavor}.user.css";
    };

  };
}
