#!/usr/bin/env bash
# Profile: chrome-compecta
# Generated by Semsumo v7.0.0
set -e

echo "Initializing chrome-compecta..."

# Switch to workspace
if [[ "4" != "0" ]] && command -v hyprctl >/dev/null 2>&1; then
    CURRENT_WORKSPACE=$(hyprctl activeworkspace -j | grep -o '"id": [0-9]*' | grep -o '[0-9]*' || echo "")
    
    if [[ "$CURRENT_WORKSPACE" != "4" ]]; then
        echo "Switching to workspace 4..."
        hyprctl dispatch workspace "4"
        sleep 1
    else
        echo "Already on workspace 4, skipping switch."
    fi
fi

echo "Starting application..."
echo "COMMAND: profile_chrome CompecTA --class CompecTA"
echo "VPN MODE: secure"

# Start application with VPN mode
case "secure" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass (mullvad-exclude)"
                mullvad-exclude profile_chrome CompecTA --class CompecTA &
            else
                echo "WARNING: mullvad-exclude not found, starting normally"
                profile_chrome CompecTA --class CompecTA &
            fi
        else
            echo "VPN not connected, starting normally"
            profile_chrome CompecTA --class CompecTA &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected! Starting without protection"
        fi
        profile_chrome CompecTA --class CompecTA &
        ;;
esac

# Save PID
APP_PID=$!
mkdir -p "/tmp/semsumo"
echo "$APP_PID" > "/tmp/semsumo/chrome-compecta.pid"
echo "Application started (PID: $APP_PID)"

# Make fullscreen if needed
if [[ "false" == "true" ]]; then
    echo "Waiting 1 seconds for application to load..."
    sleep 1
    
    if command -v hyprctl >/dev/null 2>&1; then
        echo "Making fullscreen..."
        hyprctl dispatch fullscreen 1
    fi
fi

exit 0
