#!/usr/bin/env bash
# Profile: webcord
# Generated by Semsumo v8.0.0 (Unified Edition)
set -e

readonly APP_TIMEOUT=4
readonly CHECK_INTERVAL=1
readonly WORKSPACE=5
readonly VPN_MODE="secure"
readonly FULLSCREEN=false
readonly WAIT_TIME=1

# Detect window manager
if command -v hyprctl &>/dev/null && hyprctl version &>/dev/null; then
    WM_TYPE="hyprland"
elif command -v niri &>/dev/null && [[ "$XDG_CURRENT_DESKTOP" == "niri" ]]; then
    WM_TYPE="niri"
elif [[ "$XDG_CURRENT_DESKTOP" == *"GNOME"* ]] || command -v gnome-shell &>/dev/null; then
    WM_TYPE="gnome"
else
    WM_TYPE="generic"
fi

echo "Initializing webcord on $WM_TYPE..."

# External monitor setup (GNOME only)
if [[ "$WM_TYPE" == "gnome" ]] && command -v xrandr >/dev/null 2>&1; then
    EXTERNAL_MONITOR=$(xrandr --query | grep " connected" | grep -v "eDP" | head -1 | awk '{print $1}')
    if [[ -n "$EXTERNAL_MONITOR" ]]; then
        echo "Setting $EXTERNAL_MONITOR as primary..."
        xrandr --output "$EXTERNAL_MONITOR" --primary
        sleep 1
    fi
fi

# Switch to workspace
if [[ "$WORKSPACE" != "0" ]]; then
    case "$WM_TYPE" in
    hyprland)
        if command -v hyprctl >/dev/null 2>&1; then
            CURRENT=$(hyprctl activeworkspace -j | grep -o '"id": [0-9]*' | grep -o '[0-9]*' || echo "")
            if [[ "$CURRENT" != "$WORKSPACE" ]]; then
                echo "Switching to workspace $WORKSPACE..."
                hyprctl dispatch workspace "$WORKSPACE"
                sleep 1
            fi
        fi
        ;;
    niri)
        if command -v niri >/dev/null 2>&1; then
            workspace_to_niri() {
                local ws="${1:-}"
                case "$ws" in
                    0|"") echo "$ws" ;;
                    1) echo "kenp" ;;
                    2) echo "term" ;;
                    3) echo "ai" ;;
                    4) echo "cta" ;;
                    5) echo "chat" ;;
                    6) echo "media" ;;
                    7) echo "tools" ;;
                    8) echo "mus" ;;
                    9) echo "msg" ;;
                    *) echo "$ws" ;;
                esac
            }

            NIRI_WS="$(workspace_to_niri "$WORKSPACE")"
            echo "Switching to workspace $WORKSPACE (niri: $NIRI_WS)..."
            niri msg action focus-workspace "$NIRI_WS"
            sleep 1
        fi
        ;;
    gnome|*)
        if command -v wmctrl >/dev/null 2>&1; then
            TARGET=$((WORKSPACE - 1))
            echo "Switching to workspace $WORKSPACE..."
            wmctrl -s "$TARGET"
            sleep 1
        fi
        ;;
    esac
fi

echo "Starting application..."
echo "COMMAND: webcord --class=WebCord --title=Webcord"
echo "VPN MODE: $VPN_MODE"

# Start application with VPN mode
case "$VPN_MODE" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass"
                mullvad-exclude webcord --class=WebCord --title=Webcord &
            else
                echo "WARNING: mullvad-exclude not found"
                webcord --class=WebCord --title=Webcord &
            fi
        else
            echo "VPN not connected"
            webcord --class=WebCord --title=Webcord &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected!"
        fi
        webcord --class=WebCord --title=Webcord &
        ;;
esac

APP_PID=$!
mkdir -p "/tmp/semsumo"
echo "$APP_PID" > "/tmp/semsumo/webcord.pid"
echo "Application started (PID: $APP_PID)"

# Window verification (Hyprland only)
if [[ "$WORKSPACE" != "0" && "$WM_TYPE" == "hyprland" ]] && command -v hyprctl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    echo "Verifying window on workspace $WORKSPACE..."
    ELAPSED=0
    CLASS_PATTERN="WebCord"
    
    while [[ $ELAPSED -lt $APP_TIMEOUT ]]; do
        if hyprctl clients -j 2>/dev/null | jq -e ".[] | select(.workspace.id == $WORKSPACE and (.class | test(\"$CLASS_PATTERN\"; \"i\")))" >/dev/null 2>&1; then
            echo "Window verified after ${ELAPSED}s"
            break
        fi
        sleep $CHECK_INTERVAL
        ((ELAPSED += CHECK_INTERVAL))
        if ((ELAPSED % 3 == 0)); then
            echo "Waiting... (${ELAPSED}/${APP_TIMEOUT}s)"
        fi
    done
    
    [[ $ELAPSED -ge $APP_TIMEOUT ]] && echo "WARNING: Timeout after ${APP_TIMEOUT}s"
else
    sleep $WAIT_TIME
fi

# Make fullscreen if needed
if [[ "$FULLSCREEN" == "true" ]]; then
    sleep $WAIT_TIME
    case "$WM_TYPE" in
    hyprland)
        command -v hyprctl >/dev/null 2>&1 && hyprctl dispatch fullscreen 1
        ;;
    niri)
        command -v niri >/dev/null 2>&1 && niri msg action fullscreen-window
        ;;
    gnome)
        if command -v gdbus >/dev/null 2>&1; then
            gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "global.display.get_focus_window().make_fullscreen()" >/dev/null 2>&1
        elif command -v wmctrl >/dev/null 2>&1; then
            WID=$(wmctrl -l | tail -1 | awk '{print $1}')
            [[ -n "$WID" ]] && wmctrl -i -r "$WID" -b add,fullscreen
        fi
        ;;
    esac
fi

echo "webcord initialization complete"
exit 0
