# systems/x86_64-linux/vhay/hardware-configuration.nix
# ==============================================================================
# vHAY VM hardware config (auto-generated by nixos-generate-config).
# Do not edit manually; regenerate if virtual hardware changes.
# Shared HW policy should live in modules/nixos/hardware, not here.
# ==============================================================================
#
# This file defines:
# - Imports qemu-guest profile
# - Kernel modules available on boot
# - Filesystem mounts (by UUID)
# - Swap devices
# - Default DHCP settings
# - Host platform
#
# ==============================================================================
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "virtio_pci" "floppy" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44a97622-a532-4d2c-b1fa-870d2acfe629";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/997cbe9f-363d-45d7-ae31-3de8dea1e46a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
